#include<iostream>
using namespace std;
main()
{
string name;
int adult_Ticket, child_Ticket,sold_child_Ticket,sold_adult_Ticket;
float charity,total;
cout<<"Enter name of movie";
cin>>name;
cout<<"Enter adult ticket price";
cin>>adult_Ticket;
cout<<"Enter child ticket price";
cin>>child_Ticket;
cout<<"Number of adult tickets sold";
cin>>sold_adult_Ticket;
cout<<"Number of child tickets sold";
cin>>sold_child_Ticket;
cout<<"Enter percentage of the amount to be donated to the charity";
cin>>charity;
total=(adult_Ticket*sold_adult_Ticket)+(child_Ticket*sold_child_Ticket);
float donation=(charity*total)/100;
cout<<"Given to cahrity" <<donation <<endl;
int remaining=total-donation;
cout<<"Total amount generated by the total sold tickets" <<total<<endl;
cout<<"Profit after donation is " <<remaining;
}